CC              = gcc
OBJS            = client.o
PROGRAM         = client
CFLAGS          = -g

build:          $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(PROGRAM)

clean:;         rm -f *.o *~ $(PROGRAM)

