CC              = gcc
OBJS            = server.o
PROGRAM         = server
CFLAGS          = -g

build:          $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $(PROGRAM)

clean:;         rm -f *.o *~ $(PROGRAM)

